name: tf
channels:
- defaults
- rdkit
dependencies:
- numpy
- jupyter
- pandas
- setuptools=39.1.0
- scipy
- tqdm
- mkl
- rdkit
- matplotlib
- seaborn
- scikit-learn
- hdf5
- h5py
- pip:
  - tensorflow
  - tensorflow-gpu
